<template>
  <v-layout id ="card-container">
      <v-flex xs12>
          <v-card>
            <v-card-title primary-title>
             <p class="mb-0">Resumen de reserva</p>
            </v-card-title>
             <v-divider> </v-divider>
             <v-card-text class="ml-2"> 
              
                <v-layout row> 
                  <v-flex xs6>
                    Servicio 
                  </v-flex>
                  <v-flex xs6 class="secondary--text"> 
                    {{item.id}}
                  </v-flex>
                </v-layout>
                   
                    <v-layout row> 
                  <v-flex xs4 class="secondary--text" >
                    Origen
                   
                  </v-flex>
                  <v-flex xs6 class="secondary--text"> 
                    Destino
                

                  </v-flex>
                </v-layout>

                  <v-layout row> 
                  <v-flex xs4 >
                 
                    <div class="hora-ida"> {{item.service.departure}} </div> 
                  </v-flex>
                  <v-flex xs6 class="ml-2"> 
                  
                    <div class="hora-regreso "> {{item.service.arrival}} </div> 

                  </v-flex>
                </v-layout>


                <v-layout>
                  <v-flex xs6>
                    Fecha de viaje 
                  </v-flex>
                  <v-flex xs6 class="secondary--text"> 
                  {{item.service.date}}
                  </v-flex>
                </v-layout>    
                
              </v-card-text>

            <v-card-actions>
            <v-btn  color="red" @click="mostrarAnular(item)">Anular</v-btn> 
              <v-btn  color="orange" @click="mostrarConfirmar(item)">Confirmar</v-btn>
              <v-btn  color="primary">Ver Detalles</v-btn>
            </v-card-actions>
          </v-card>
        </v-flex>
   
  </v-layout>
</template>

<script>
  // <img :src="avatar + auth.name + '?font-size=0.45&length=2&background=F17B31&color=fff'">
  // avatar: 'https://ui-avatars.com/api/?name=',
  import moment from 'moment'
  import {mapGetters} from 'vuex'
  import axios from 'axios'
  import API from '@pi/app'

  export default {
     props: ['item'],
    name: 'tickets',
    data() {
      return {
      }
    },
    mounted () {
     // console.log(this.item)
    },
    computed: {
      ...mapGetters({
        search: ['Booking/current'],
        ruta: ['Booking/ruta']
      }),
    
    },
    methods: {
       mostrarAnular(item) {
         console.log(item)
           this.$store.dispatch('Booking/set_servicioAnular', {
          servicioAnular: item
        }); 
        this.$store.dispatch('Booking/set_anular', {
          anular: true
        });  
      },
      mostrarConfirmar (item) {
         this.$store.dispatch('Booking/set_confirmar', {
          confirmar: true
        });  
         this.$store.dispatch('Booking/set_servicioConfirmar', {
          servicioConfirmar: item
        }); 

      }
    },
    watch: {
    
    }
  }
</script>

<style>

  #card-container {
    width: 100%
  }

  #card-container:hover {
   
  }

    .hora-ida {
        position: relative;
        background: #1565c0;
        text-align: center;
        height: 32px;
    }

    .hora-regreso:before {
        content: '';
        border-left: 16px solid #fff;
        border-top: 16px solid transparent;
        border-bottom: 16px solid transparent;
        position: absolute;
        top: 0;
        left: 0;
       
    
    }

    .hora-ida:after {
        content: '';
        border-left: 16px solid #1565c0;
        border-top: 16px solid transparent;
        border-bottom: 16px solid transparent;
        position: absolute;
        top: 0;
        left: 100%;
        z-index: 20;   
    }

    .hora-regreso {
        text-align: center;
        position: relative;
        background: #1565c0;
        height: 32px;
         width: 90%;
       
    }

    .shadow-drop-2-center {
      -webkit-animation: shadow-drop-2-center 0.4s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
              animation: shadow-drop-2-center 0.4s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    }

    /* ----------------------------------------------
 * Generated by Animista on 2018-11-27 18:25:10
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shadow-drop-2-center
 * ----------------------------------------
 */
@-webkit-keyframes shadow-drop-2-center {
  0% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    box-shadow: 0 0 0 0 rgba(0, 0, 0, 0);
  }
  100% {
    -webkit-transform: translateZ(50px);
            transform: translateZ(50px);
    box-shadow: 0 0 20px 0px rgba(0, 0, 0, 0.35);
  }
}
@keyframes shadow-drop-2-center {
  0% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    box-shadow: 0 0 0 0 rgba(0, 0, 0, 0);
  }
  100% {
    -webkit-transform: translateZ(50px);
            transform: translateZ(50px);
    box-shadow: 0 0 20px 0px rgba(0, 0, 0, 0.35);
  }
}


</style>
